ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/common
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -I $(srctree)/drivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_LC898123F40) += lc898123f40_iris.o
